### ISSUE TITLE
Feature Request - Support for rendering deltas to other formats

### ISSUE THREAD

**Issue by tmbb** [everzet/text_delta#3]
I'm thinking mostly of HTML, but XML, latex and PDF are other alternatives.
In node there is this library: [quilljs-renderer](https://www.npmjs.com/package/quilljs-renderer).

On the other hand, maybe this should go to some other package.

**Comment by everzet** [comment]
Yeah, I'd say it should be another library or a set of libraries.

**Comment by everzet** [comment]
I'll likely get there in a short time :)
